version: '3'

services:
  app:
    container_name: springboot
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    image: postgres
#    restart: always
    environment:
      POSTGRES_PASSWORD: aqwsde322
      POSTGRES_USER: postgres
      POSTGRES_DB: hotel
    ports:
      - "5433:5432"

